"""src/gate.py — 4-level quality gate engine

Implements a 4-level quality gate system that runs checks at different
stages of the pipeline lifecycle:

  GateLevel.POST_GEN (0): <5s  checks on generated files
  GateLevel.COMMIT  (1): <30s checks before committing code
  GateLevel.PUSH    (2): <5min checks before pushing to remote
  GateLevel.CI      (3): CI-level comprehensive checks

Each gate level runs a set of check functions, collects results, and returns
a unified GateResult with pass/fail status, timing, and failure details.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

try:
    from config import get_config
except (ModuleNotFoundError, ImportError):
    from src.config import get_config

try:
    from thresholds_loader import get_threshold
except (ModuleNotFoundError, ImportError):
    from src.thresholds_loader import get_threshold


# ───────────────────────────────────────────────────────────────
# GateLevel enum
# ───────────────────────────────────────────────────────────────

class GateLevel(Enum):
    """4-level quality gate, each with a target latency budget."""
    POST_GEN = 0   # <5s — quick scans after code generation
    COMMIT = 1     # <30s — pre-commit quality checks
    PUSH = 2       # <5min — pre-push integration / spec checks
    CI = 3         # CI — comprehensive pipeline validation


# ───────────────────────────────────────────────────────────────
# GateResult dataclass
# ───────────────────────────────────────────────────────────────

@dataclass
class GateResult:
    """Unified result from a gate run.

    Attributes:
        passed: True if all checks in this gate passed.
        level: The GateLevel this result belongs to.
        checks_run: Total number of checks executed.
        checks_passed: Number of checks that passed.
        failures: List of (check_name, reason) tuples for failed checks.
        duration_ms: Wall-clock duration of the gate run in milliseconds.
    """
    passed: bool
    level: GateLevel
    checks_run: int
    checks_passed: int
    failures: List[Tuple[str, str]] = field(default_factory=list)
    duration_ms: float = 0.0


# ───────────────────────────────────────────────────────────────
# Check type alias
# ───────────────────────────────────────────────────────────────

CheckFunc = Callable[..., Tuple[bool, str]]


# ───────────────────────────────────────────────────────────────
# Core: run_checks
# ───────────────────────────────────────────────────────────────

def run_checks(
    checks: List[Tuple[str, CheckFunc, tuple]],
    level: GateLevel,
    timeout: float,
) -> GateResult:
    """Run a list of checks and aggregate results into a GateResult.

    Parameters:
        checks: List of (name, callable, args) tuples.
        level: The GateLevel for reporting / context.
        timeout: Total timeout in seconds (soft — best-effort).

    Returns:
        GateResult with aggregated pass/fail data.
    """
    start = time.perf_counter()
    failures: List[Tuple[str, str]] = []
    checks_run = 0
    checks_passed = 0

    deadline = start + timeout

    for name, func, args in checks:
        if time.perf_counter() > deadline:
            failures.append((name, "Gate timeout exceeded"))
            checks_run += 1
            continue

        try:
            passed, reason = func(*args)
            checks_run += 1
            if passed:
                checks_passed += 1
            else:
                failures.append((name, reason))
        except (ValueError, TypeError, KeyError, RuntimeError, OSError, ConnectionError, TimeoutError, ImportError, AttributeError) as exc:
            checks_run += 1
            failures.append((name, f"Check raised exception: {exc}"))

    elapsed = (time.perf_counter() - start) * 1000.0
    all_passed = len(failures) == 0 and checks_run > 0

    return GateResult(
        passed=all_passed,
        level=level,
        checks_run=checks_run,
        checks_passed=checks_passed,
        failures=failures,
        duration_ms=elapsed,
    )


# ═══════════════════════════════════════════════════════════════
# Level 0 checks — POST_GEN (<5s)
# ═══════════════════════════════════════════════════════════════

def _check_ai_origin_mark(file_path: Path) -> Tuple[bool, str]:
    """Check that the file contains an AI-origin marker comment.

    Looks for markers like '# AI-generated', '// AI-generated',
    'Generated by AI', or the standard HERMES-AI marker.
    """
    try:
        content = file_path.read_text(encoding="utf-8", errors="replace")
    except (OSError, UnicodeDecodeError):
        return False, f"Cannot read file: {file_path}"

    markers = [
        r"#\s*AI.generated",
        r"//\s*AI.generated",
        r"Generated by AI",
        r"HERMES.AI",
        r"@ai.generated",
        r"@generated",
    ]
    for marker in markers:
        if re.search(marker, content, re.IGNORECASE):
            return True, "AI origin mark found"

    return False, "No AI origin mark found in file"


def _check_hardcoded_secrets(file_path: Path) -> Tuple[bool, str]:
    """Scan for hardcoded secrets like API keys, passwords, tokens.

    Returns (True, ...) if NO secrets are found (i.e. check passes).
    """
    try:
        content = file_path.read_text(encoding="utf-8", errors="replace")
    except (OSError, UnicodeDecodeError):
        return True, "Skipped — cannot read file"

    # Patterns that suggest hardcoded secrets
    min_secret_length = get_threshold("gate.secrets.min_secret_length", 8)
    secret_patterns = [
        (r'api_key\s*=\s*["\'](?!\$\{)[^"\'\s]{' + str(min_secret_length) + r',}["\']', "Hardcoded api_key"),
        (r'password\s*=\s*["\'][^"\']+["\']', "Hardcoded password"),
        (r'secret\s*=\s*["\'][^"\']+["\']', "Hardcoded secret"),
        (r'token\s*=\s*["\'][^"\']{' + str(min_secret_length) + r',}["\']', "Hardcoded token"),
        (r'access_key\s*=\s*["\'](?!\$\{)[^"\'\s]{' + str(min_secret_length) + r',}["\']', "Hardcoded access_key"),
        (r'AWS_SECRET_ACCESS_KEY\s*=\s*["\'][^"\']+["\']', "Hardcoded AWS secret key"),
    ]

    found: List[str] = []
    for pattern, label in secret_patterns:
        if re.search(pattern, content, re.IGNORECASE):
            found.append(label)

    if found:
        return False, f"Hardcoded secrets detected: {', '.join(found)}"
    return True, "No hardcoded secrets found"


def _check_dangerous_patterns(file_path: Path) -> Tuple[bool, str]:
    """Scan for dangerous code patterns: eval, exec, os.system, subprocess shell=True.

    Returns (True, ...) if NO dangerous patterns are found.
    """
    try:
        content = file_path.read_text(encoding="utf-8", errors="replace")
    except (OSError, UnicodeDecodeError):
        return True, "Skipped — cannot read file"

    dangerous = [
        (r'\beval\s*\(', "eval() call"),
        (r'\bexec\s*\(', "exec() call"),
        (r'\bos\.system\s*\(', "os.system() call"),
        (r'\bos\.popen\s*\(', "os.popen() call"),
        (r'shell\s*=\s*True', "subprocess with shell=True"),
        (r'__import__\s*\(\s*["\']os["\']', "dynamic os import"),
        (r'compile\s*\([^)]*\beval\b', "compile() with eval mode"),
        (r'pickle\.loads?\s*\(', "pickle deserialization (potential RCE)"),
    ]

    found: List[str] = []
    for pattern, label in dangerous:
        if re.search(pattern, content):
            found.append(label)

    if found:
        return False, f"Dangerous patterns: {', '.join(found)}"
    return True, "No dangerous patterns found"


def _check_path_safety(file_path: Path) -> Tuple[bool, str]:
    """Check for unsafe path operations: '../' traversal, absolute paths to
    sensitive locations, dynamic path construction without validation.

    Returns (True, ...) if path usage appears safe.
    """
    try:
        content = file_path.read_text(encoding="utf-8", errors="replace")
    except (OSError, UnicodeDecodeError):
        return True, "Skipped — cannot read file"

    unsafe = [
        (r'\.\./\.\./', "Multiple ../ traversal"),
        (r'/etc/passwd', "References /etc/passwd"),
        (r'/etc/shadow', "References /etc/shadow"),
        (r'C:\\Windows\\System32', "References Windows system directory"),
        (r'os\.path\.join\s*\([^)]*\.\./', "Path join with ../"),
        (r'/root/', "References /root/ (privileged)"),
    ]

    found: List[str] = []
    for pattern, label in unsafe:
        if re.search(pattern, content, re.IGNORECASE):
            found.append(label)

    if found:
        return False, f"Unsafe path patterns: {', '.join(found)}"
    return True, "Path usage appears safe"


# ═══════════════════════════════════════════════════════════════
# Level 1 checks — COMMIT (<30s)
# ═══════════════════════════════════════════════════════════════

def _check_feature_lint(project_name: str) -> Tuple[bool, str]:
    """Run a basic lint pass on the project's source files.

    Checks for syntax validity and common code-quality issues.
    This is a lightweight check — no external linter required.
    """
    try:
        config = get_config()
    except (ValueError, TypeError, KeyError, RuntimeError, OSError, ConnectionError, TimeoutError, ImportError, AttributeError):
        return False, "Cannot load pipeline config"

    base_dir = config.base_dir
    proj_dir = base_dir / project_name

    if not proj_dir.exists():
        return False, f"Project directory does not exist: {proj_dir}"

    src_dir = proj_dir / config.src_dir_name
    if not src_dir.exists():
        return False, f"Source directory does not exist: {src_dir}"

    py_files = list(src_dir.rglob("*.py"))
    if not py_files:
        return True, "No Python source files to lint"

    # Basic lint checks
    issues: List[str] = []

    trailing_ws_threshold = get_threshold('gate.lint.trailing_whitespace_threshold', 20)
    long_line_threshold = get_threshold('gate.lint.long_line_threshold', 150)
    long_line_count_threshold = get_threshold('gate.lint.long_line_count_threshold', 5)
    blank_ws_threshold = get_threshold('gate.lint.blank_whitespace_threshold', 10)

    for py_file in py_files:
        try:
            content = py_file.read_text(encoding='utf-8')
        except (OSError, UnicodeDecodeError):
            issues.append(f'Cannot read {py_file.name}')
            continue

        # Check for trailing whitespace on lines
        trailing = [i + 1 for i, line in enumerate(content.splitlines())
                     if line.rstrip() != line]
        if len(trailing) > trailing_ws_threshold:
            issues.append(f'{py_file.name}: {len(trailing)} lines with trailing whitespace')

        # Check for lines > threshold chars
        long_lines = [i + 1 for i, line in enumerate(content.splitlines())
                      if len(line) > long_line_threshold]
        if len(long_lines) > long_line_count_threshold:
            issues.append(f'{py_file.name}: {len(long_lines)} lines exceed {long_line_threshold} chars')

        # Check for blank lines with whitespace
        blank_ws = [i + 1 for i, line in enumerate(content.splitlines())
                    if line.strip() == '' and len(line) > 0]
        if len(blank_ws) > blank_ws_threshold:
            issues.append(f'{py_file.name}: {len(blank_ws)} blank lines contain whitespace')

    if issues:
        return False, f"Lint issues: {'; '.join(issues[:3])}"
    return True, "Lint check passed"


def _check_feature_tests(project_name: str) -> Tuple[bool, str]:
    """Check that test files exist and have basic structural integrity.

    Verifies that each source module has a corresponding test file,
    and that test files contain actual test functions.
    """
    try:
        config = get_config()
    except (ValueError, TypeError, KeyError, RuntimeError, OSError, ConnectionError, TimeoutError, ImportError, AttributeError):
        return False, "Cannot load pipeline config"

    base_dir = config.base_dir
    proj_dir = base_dir / project_name

    if not proj_dir.exists():
        return False, f"Project directory does not exist: {proj_dir}"

    src_dir = proj_dir / config.src_dir_name
    tests_dir = proj_dir / config.tests_dir_name

    src_files = list(src_dir.rglob("*.py")) if src_dir.exists() else []
    test_files = set()
    if tests_dir.exists():
        for tf in tests_dir.rglob("*.py"):
            test_files.add(tf.stem)

    # Check: for each source module, expect a test_<module> or <module>_test
    missing_tests: List[str] = []
    for src_file in src_files:
        if src_file.name.startswith("__"):
            continue
        stem = src_file.stem
        expected_stems = {f"test_{stem}", f"{stem}_test"}
        if not expected_stems & test_files:
            missing_tests.append(stem)

    if missing_tests:
        return False, f"Missing test files for: {', '.join(missing_tests[:5])}"

    # Verify test files have at least one test function
    empty_tests: List[str] = []
    for tf_path in tests_dir.rglob("*.py"):
        try:
            content = tf_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if not re.search(r'def\s+test_', content):
            empty_tests.append(tf_path.name)

    if empty_tests:
        return False, f"Test files without test functions: {', '.join(empty_tests[:3])}"

    return True, f"Tests OK — {len(src_files)} source files, coverage good"


def _check_no_hermes_code(project_name: str) -> Tuple[bool, str]:
    """Ensure no Hermes internal code leaks into the generated project.

    Scans for Hermes-specific imports, agent scaffold patterns,
    and internal tool references that shouldn't appear in user projects.
    """
    try:
        config = get_config()
    except (ValueError, TypeError, KeyError, RuntimeError, OSError, ConnectionError, TimeoutError, ImportError, AttributeError):
        return False, "Cannot load pipeline config"

    base_dir = config.base_dir
    proj_dir = base_dir / project_name

    if not proj_dir.exists():
        return False, f"Project directory does not exist: {proj_dir}"

    src_dir = proj_dir / config.src_dir_name
    if not src_dir.exists():
        return True, "No source directory"

    py_files = list(src_dir.rglob("*.py"))
    if not py_files:
        return True, "No Python files to scan"

    hermes_markers = [
        (r'from\s+hermes', "Hermes import"),
        (r'import\s+hermes', "Hermes import"),
        (r'Nous\s+Research', "Nous Research reference"),
        (r'agent_loop\s*\(', "agent_loop call"),
        (r'HermesAgent', "HermesAgent class reference"),
        (r'tool_use\s*\(', "tool_use call"),
        (r'mcp_server', "MCP server reference"),
    ]

    found: List[str] = []
    for py_file in py_files:
        try:
            content = py_file.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for pattern, label in hermes_markers:
            if re.search(pattern, content, re.IGNORECASE):
                found.append(f"{py_file.name}: {label}")

    if found:
        return False, f"Hermes code leak: {'; '.join(found[:3])}"
    return True, "No Hermes code leakage detected"


def _check_phase_requirements(project_name: str) -> Tuple[bool, str]:
    """Check that the current phase requirements are met.

    Verifies presence of required artifacts:
      - SOUL.md, AGENTS.md, progress.md exist
      - features.json is valid
      - State store reports current phase
    """
    try:
        config = get_config()
    except (ValueError, TypeError, KeyError, RuntimeError, OSError, ConnectionError, TimeoutError, ImportError, AttributeError):
        return False, "Cannot load pipeline config"

    base_dir = config.base_dir
    proj_dir = base_dir / project_name

    if not proj_dir.exists():
        return False, f"Project directory does not exist: {proj_dir}"

    required_files = ["SOUL.md", "AGENTS.md", "progress.md", "features.json"]
    missing: List[str] = []
    for fname in required_files:
        if not (proj_dir / fname).exists():
            missing.append(fname)

    if missing:
        return False, f"Missing required files: {', '.join(missing)}"

    # Check features.json validity
    import json
    features_path = proj_dir / "features.json"
    try:
        data = json.loads(features_path.read_text(encoding="utf-8"))
        if not isinstance(data, dict) or "features" not in data:
            return False, "features.json missing 'features' key"
    except (json.JSONDecodeError, OSError) as e:
        return False, f"features.json invalid: {e}"

    return True, "Phase requirements met"


# ═══════════════════════════════════════════════════════════════
# Level 2 checks — PUSH (<5min)
# ═══════════════════════════════════════════════════════════════

def _check_integrate(project_name: str) -> Tuple[bool, str]:
    """Run integration-level checks across modules.

    Verifies that cross-module imports are consistent and that
    the project's module graph has no broken dependencies.
    """
    try:
        config = get_config()
    except (ValueError, TypeError, KeyError, RuntimeError, OSError, ConnectionError, TimeoutError, ImportError, AttributeError):
        return False, "Cannot load pipeline config"

    base_dir = config.base_dir
    proj_dir = base_dir / project_name

    if not proj_dir.exists():
        return False, f"Project directory does not exist: {proj_dir}"

    src_dir = proj_dir / config.src_dir_name
    if not src_dir.exists():
        return False, "No source directory"

    py_files = list(src_dir.rglob("*.py"))
    if not py_files:
        return True, "No Python files to integrate"

    # Build module graph and check for broken imports
    module_names: Dict[str, Path] = {}
    for pf in py_files:
        rel = pf.relative_to(src_dir)
        mod_name = str(rel.with_suffix("")).replace("\\", ".").replace("/", ".")
        module_names[mod_name] = pf

    broken_imports: List[str] = []
    for pf in py_files:
        try:
            content = pf.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        # Extract import statements
        import_patterns = re.findall(
            r'^(?:from|import)\s+([a-zA-Z_][a-zA-Z0-9_.]*)',
            content, re.MULTILINE
        )
        for imp in import_patterns:
            # Skip stdlib and third-party; only check project-local
            if imp.startswith(("src.", project_name.lower())):
                # Normalize
                clean = imp
                if clean.startswith("src."):
                    clean = clean[4:]
                # Check each prefix
                parts = clean.split(".")
                for i in range(len(parts), 0, -1):
                    candidate = ".".join(parts[:i])
                    if candidate in module_names:
                        break
                else:
                    broken_imports.append(f"{pf.name}: {imp}")

    if broken_imports:
        return False, f"Broken internal imports: {'; '.join(broken_imports[:5])}"
    return True, "Integration check passed"


def _check_spec_conformance(project_name: str) -> Tuple[bool, str]:
    """Verify conformance between architecture spec and implementation.

    Checks that every module described in specs/architecture.md has a
    corresponding source file, and that key interfaces are implemented.
    """
    try:
        config = get_config()
    except (ValueError, TypeError, KeyError, RuntimeError, OSError, ConnectionError, TimeoutError, ImportError, AttributeError):
        return False, "Cannot load pipeline config"

    base_dir = config.base_dir
    proj_dir = base_dir / project_name

    if not proj_dir.exists():
        return False, f"Project directory does not exist: {proj_dir}"

    arch_path = proj_dir / "specs" / "architecture.md"
    if not arch_path.exists():
        return True, "No architecture.md — skipping spec conformance"

    try:
        arch_content = arch_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return True, "Cannot read architecture.md — skipping"

    # Extract module names mentioned in architecture.md
    # Look for code blocks and module references
    module_refs = set(re.findall(
        r'(?:module|component|service|class)\s+[`"]?([a-zA-Z_][a-zA-Z0-9_]*)',
        arch_content, re.IGNORECASE
    ))

    src_dir = proj_dir / config.src_dir_name
    actual_modules: set = set()
    if src_dir.exists():
        for pf in src_dir.rglob("*.py"):
            if pf.name.startswith("__"):
                continue
            actual_modules.add(pf.stem.lower())

    # Check that spec modules have implementations
    unmatched: List[str] = []
    for mod_ref in module_refs:
        mod_lower = mod_ref.lower()
        if mod_lower not in actual_modules:
            # Try snake_case variants
            snake = re.sub(r'(?<!^)(?=[A-Z])', '_', mod_ref).lower()
            if snake not in actual_modules:
                unmatched.append(mod_ref)

    if unmatched:
        return False, f"Spec modules without implementation: {', '.join(unmatched)}"
    return True, "Spec conformance OK"


def _check_evaluate(project_name: str) -> Tuple[bool, str]:
    """Evaluate overall code quality metrics.

    Computes a simple quality score based on:
      - Code/test ratio
      - Documentation presence
      - Code complexity heuristics
    """
    try:
        config = get_config()
    except (ValueError, TypeError, KeyError, RuntimeError, OSError, ConnectionError, TimeoutError, ImportError, AttributeError):
        return False, "Cannot load pipeline config"

    base_dir = config.base_dir
    proj_dir = base_dir / project_name

    if not proj_dir.exists():
        return False, f"Project directory does not exist: {proj_dir}"

    src_dir = proj_dir / config.src_dir_name
    tests_dir = proj_dir / config.tests_dir_name

    src_files = list(src_dir.rglob("*.py")) if src_dir.exists() else []
    test_files = list(tests_dir.rglob("*.py")) if tests_dir.exists() else []

    src_lines = 0
    docstring_count = 0
    for sf in src_files:
        try:
            content = sf.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        src_lines += len(content.splitlines())
        # Count docstrings (triple-quoted strings)
        docstring_count += len(re.findall(r'"""(?:[^"]|"(?!""))*?"""', content, re.DOTALL))
        docstring_count += len(re.findall(r"'''(?:[^']|'(?!''))*?'''", content, re.DOTALL))

    test_lines = sum(
        len(tf.read_text(encoding="utf-8").splitlines())
        for tf in test_files
        if tf.exists()
    ) if test_files else 0

    # Heuristics
    issues: List[str] = []

    min_test_ratio = get_threshold('gate.quality.min_test_ratio', 0.1)
    min_doc_ratio = get_threshold('gate.quality.min_doc_ratio', 0.5)

    # Check test-to-code ratio
    if src_lines > 0:
        ratio = test_lines / src_lines
        if ratio < min_test_ratio:
            issues.append(f"Low test ratio: {ratio:.1%}")
    elif test_lines == 0:
        issues.append("No tests found")

    # Check documentation coverage
    if src_lines > 0:
        doc_ratio = docstring_count / max(src_lines / 50, 1)
        if doc_ratio < min_doc_ratio:
            issues.append(f"Low documentation: {docstring_count} docstrings for {src_lines} LOC")

    if issues:
        return False, f"Quality issues: {'; '.join(issues)}"
    return True, "Evaluation passed"


def _check_inspector_review(project_name: str) -> Tuple[bool, str]:
    """Check that an inspector review has been completed.

    Looks for review artifacts like REVIEW.md or inspector_checkpoint
    in the project's state store.
    """
    try:
        config = get_config()
    except (ValueError, TypeError, KeyError, RuntimeError, OSError, ConnectionError, TimeoutError, ImportError, AttributeError):
        return False, "Cannot load pipeline config"

    base_dir = config.base_dir
    proj_dir = base_dir / project_name

    if not proj_dir.exists():
        return False, f"Project directory does not exist: {proj_dir}"

    # Look for REVIEW.md or similar review artifact
    review_files = list(proj_dir.rglob("REVIEW*"))
    if review_files:
        return True, f"Review artifact found: {review_files[0].name}"

    # Check state store for inspector checkpoint
    db_path = proj_dir / config.db_name
    if db_path.exists():
        try:
            import sqlite3
            conn = sqlite3.connect(str(db_path))
            cur = conn.execute(
                "SELECT COUNT(*) FROM checkpoints WHERE phase LIKE '%review%' OR phase LIKE '%inspector%'"
            )
            count = cur.fetchone()[0]
            conn.close()
            if count > 0:
                return True, f"Inspector checkpoint found ({count} records)"
        except (sqlite3.Error, OSError):
            pass

    return False, "No inspector review found — run inspector before pushing"


def _check_all_features_passed(project_name: str) -> Tuple[bool, str]:
    """Verify that all features in features.json have status 'passed'."""
    try:
        config = get_config()
    except (ValueError, TypeError, KeyError, RuntimeError, OSError, ConnectionError, TimeoutError, ImportError, AttributeError):
        return False, "Cannot load pipeline config"

    base_dir = config.base_dir
    proj_dir = base_dir / project_name

    if not proj_dir.exists():
        return False, f"Project directory does not exist: {proj_dir}"

    features_path = proj_dir / "features.json"
    if not features_path.exists():
        return False, "features.json not found"

    import json
    try:
        data = json.loads(features_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        return False, f"features.json invalid: {e}"

    features = data.get("features", [])
    if not isinstance(features, list):
        return False, "features.json 'features' is not a list"

    not_passed: List[str] = []
    for feat in features:
        if not isinstance(feat, dict):
            continue
        status = feat.get("status", "unknown")
        if status != "passed":
            not_passed.append(f"{feat.get('id', '?')}:{status}")

    if not_passed:
        return False, f"Features not passed: {', '.join(not_passed[:5])}"
    return True, "All features passed"


def _check_no_p0_remaining(project_name: str) -> Tuple[bool, str]:
    """Check that no P0-critical issues remain unresolved.

    Scans for TODO/FIXME/HACK/P0 markers in source code.
    """
    try:
        config = get_config()
    except (ValueError, TypeError, KeyError, RuntimeError, OSError, ConnectionError, TimeoutError, ImportError, AttributeError):
        return False, "Cannot load pipeline config"

    base_dir = config.base_dir
    proj_dir = base_dir / project_name

    if not proj_dir.exists():
        return False, f"Project directory does not exist: {proj_dir}"

    src_dir = proj_dir / config.src_dir_name
    if not src_dir.exists():
        return True, "No source directory"

    py_files = list(src_dir.rglob("*.py"))
    if not py_files:
        return True, "No Python files"

    p0_patterns = [
        (r'P0', "P0 marker"),
        (r'FIXME', "FIXME"),
        (r'HACK', "HACK"),
        (r'XXX\s*:', "XXX comment"),
        (r'CRITICAL', "CRITICAL marker"),
    ]

    found: List[str] = []
    for py_file in py_files:
        try:
            content = py_file.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for pattern, label in p0_patterns:
            if re.search(pattern, content):
                found.append(f"{py_file.name}: {label}")

    if found:
        return False, f"P0 items remaining: {'; '.join(found[:5])}"
    return True, "No P0 items remaining"


# ═══════════════════════════════════════════════════════════════
# Public gate API — per-level entry points
# ═══════════════════════════════════════════════════════════════

def gate_post_generate(file_path: str) -> GateResult:
    """Run POST_GEN gate checks on a newly generated file.

    Target: <5 seconds. Scans for AI origin markers, hardcoded secrets,
    dangerous patterns, and path safety issues.

    Parameters:
        file_path: Path to the generated file to check.

    Returns:
        GateResult with aggregated pass/fail data.
    """
    path = Path(file_path)
    checks: List[Tuple[str, CheckFunc, tuple]] = [
        ("CheckAIOriginMark", _check_ai_origin_mark, (path,)),
        ("CheckHardcodedSecrets", _check_hardcoded_secrets, (path,)),
        ("CheckDangerousPatterns", _check_dangerous_patterns, (path,)),
        ("CheckPathSafety", _check_path_safety, (path,)),
    ]
    return run_checks(checks, GateLevel.POST_GEN, timeout=get_threshold("gate.timeouts.post_gen", 5.0))


def gate_commit(project_name: str) -> GateResult:
    """Run COMMIT gate checks before committing code.

    Target: <30 seconds. Runs lint, tests, Hermes code leak detection,
    and phase requirement validation.

    Parameters:
        project_name: Name of the project to check.

    Returns:
        GateResult with aggregated pass/fail data.
    """
    checks: List[Tuple[str, CheckFunc, tuple]] = [
        ("CheckFeatureLint", _check_feature_lint, (project_name,)),
        ("CheckFeatureTests", _check_feature_tests, (project_name,)),
        ("CheckNoHermesCode", _check_no_hermes_code, (project_name,)),
        ("CheckPhaseRequirements", _check_phase_requirements, (project_name,)),
    ]
    return run_checks(checks, GateLevel.COMMIT, timeout=get_threshold("gate.timeouts.commit", 30.0))


def gate_push(project_name: str) -> GateResult:
    """Run PUSH gate checks before pushing to remote.

    Target: <5 minutes. Runs integration, spec conformance, evaluation,
    inspector review, all-features-passed, and no-P0-remaining checks.

    Parameters:
        project_name: Name of the project to check.

    Returns:
        GateResult with aggregated pass/fail data.
    """
    checks: List[Tuple[str, CheckFunc, tuple]] = [
        ("CheckIntegrate", _check_integrate, (project_name,)),
        ("CheckSpecConformance", _check_spec_conformance, (project_name,)),
        ("CheckEvaluate", _check_evaluate, (project_name,)),
        ("CheckInspectorReview", _check_inspector_review, (project_name,)),
        ("CheckAllFeaturesPassed", _check_all_features_passed, (project_name,)),
        ("CheckNoP0Remaining", _check_no_p0_remaining, (project_name,)),
    ]
    return run_checks(checks, GateLevel.PUSH, timeout=get_threshold("gate.timeouts.push", 300.0))


def gate_ci(project_name: str) -> GateResult:
    """Run CI gate checks — comprehensive pipeline validation.

    Target: flexible. Runs all PUSH-level checks plus any additional
    CI-specific checks. Currently delegates to gate_push.

    Parameters:
        project_name: Name of the project to check.

    Returns:
        GateResult with aggregated pass/fail data.
    """
    # CI runs the same checks as PUSH but can be extended with additional checks
    result = gate_push(project_name)
    # Re-tag level as CI
    result.level = GateLevel.CI
    return result


# ───────────────────────────────────────────────────────────────
# Convenience: run gate by level name
# ───────────────────────────────────────────────────────────────

_GATE_RUNNERS: Dict[GateLevel, Callable[[str], GateResult]] = {
    GateLevel.POST_GEN: gate_post_generate,
    GateLevel.COMMIT: gate_commit,
    GateLevel.PUSH: gate_push,
    GateLevel.CI: gate_ci,
}


def run_gate(level: GateLevel, target: str) -> GateResult:
    """Run a gate by level with the given target.

    Parameters:
        level: The GateLevel to run.
        target: File path (for POST_GEN) or project name (for others).

    Returns:
        GateResult with aggregated pass/fail data.
    """
    runner = _GATE_RUNNERS.get(level)
    if runner is None:
        return GateResult(
            passed=False,
            level=level,
            checks_run=0,
            checks_passed=0,
            failures=[("run_gate", f"Unknown gate level: {level}")],
        )
    return runner(target)


# ───────────────────────────────────────────────────────────────
# Module-level test / self-check
# ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys

    def _demo_gate_post_gen() -> None:
        """Quick smoke test for POST_GEN gate."""
        import tempfile

        # Create a temp file with some issues
        tmp = tempfile.NamedTemporaryFile(
            mode="w", suffix=".py", delete=False, encoding="utf-8"
        )
        tmp.write('# AI-generated module\n')
        tmp.write('import os\n')
        tmp.write('\n')
        tmp.write('def run_command(cmd):\n')
        tmp.write('    """Execute a shell command."""\n')
        tmp.write('    os.system(cmd)  # DANGEROUS\n')
        tmp.write('\n')
        tmp.write("password = 'admin123'  # SECRET\n")
        tmp.write("api_key = 'sk-1234567890abcdef'  # SECRET\n")
        tmp.close()

        print("=== POST_GEN gate demo ===")
        result = gate_post_generate(tmp.name)
        print(f"  Passed: {result.passed}")
        print(f"  Checks run: {result.checks_run}")
        print(f"  Checks passed: {result.checks_passed}")
        print(f"  Duration: {result.duration_ms:.1f}ms")
        if result.failures:
            print(f"  Failures:")
            for name, reason in result.failures:
                print(f"    - {name}: {reason}")

        Path(tmp.name).unlink(missing_ok=True)
        print()

    def _demo_gate_commit() -> None:
        """Quick smoke test for COMMIT gate (needs a real project)."""
        print("=== COMMIT gate demo ===")
        result = gate_commit("nonexistent_project")
        print(f"  Passed: {result.passed}")
        print(f"  Duration: {result.duration_ms:.1f}ms")
        if result.failures:
            for name, reason in result.failures:
                print(f"    - {name}: {reason}")
        print()

    def _demo_gate_push() -> None:
        """Quick smoke test for PUSH gate."""
        print("=== PUSH gate demo ===")
        result = gate_push("nonexistent_project")
        print(f"  Passed: {result.passed}")
        print(f"  Duration: {result.duration_ms:.1f}ms")
        if result.failures:
            for name, reason in result.failures:
                print(f"    - {name}: {reason}")
        print()

    def _demo_run_gate() -> None:
        """Demo the generic run_gate dispatcher."""
        print("=== run_gate demo ===")
        result = run_gate(GateLevel.PUSH, "nonexistent_project")
        print(f"  GateLevel: {result.level.name}")
        print(f"  Passed: {result.passed}")
        print()

    if "--demo" in sys.argv or len(sys.argv) == 1:
        _demo_gate_post_gen()
        _demo_gate_commit()
        _demo_gate_push()
        _demo_run_gate()
